# Generated by Django 5.0.2 on 2025-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
